const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA=path.join(ROOT,'data'),UPLOADS=path.join(PUBLIC,'uploads'),SKINS=path.join(UPLOADS,'skins'),PORTFOLIO=path.join(UPLOADS,'portfolio'),RECEIPTS=path.join(UPLOADS,'receipts');
[DATA,SKINS,PORTFOLIO,RECEIPTS].forEach(x=>fs.mkdirSync(x,{recursive:true}));
const env={}; try{for(const line of fs.readFileSync(path.join(ROOT,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z_][\w]*)\s*=\s*(.*)\s*$/);if(m)env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')}}catch{}
const PORT=3001, USER=env.ADMIN_USERNAME||'pouria134', PASS=env.ADMIN_PASSWORD||'pouriaabbasi134';
const services={'thumbnail-basic':35000,'thumbnail-pro':50000,'thumbnail-god':60000,'profile':45000,'channel-art':45000};
const names={'thumbnail-basic':'تامنیل اقتصادی','thumbnail-pro':'تامنیل حرفه‌ای','thumbnail-god':'تامنیل گاد','profile':'پروفایل','channel-art':'چنل آرت'};
const dbFile=path.join(DATA,'db.json'); let db={orders:[],tickets:[],portfolio:[],nextOrder:1,nextTicket:1,nextPortfolio:1}; try{Object.assign(db,JSON.parse(fs.readFileSync(dbFile,'utf8')))}catch{} function save(){fs.writeFileSync(dbFile,JSON.stringify(db,null,2),'utf8')}
const sessions=new Set();
const paymentDrafts=new Map();
function send(res,status,data,headers={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...headers});res.end(JSON.stringify(data))}
function text(res,status,msg){res.writeHead(status,{'Content-Type':'text/html; charset=utf-8'});res.end(msg)}
function cookie(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('sid='))?.slice(4)}
function admin(req){return sessions.has(cookie(req))}
function body(req){return new Promise((resolve,reject)=>{let a=[];let n=0;req.on('data',c=>{n+=c.length;if(n>20*1024*1024){req.destroy();reject(new Error('حجم فایل زیاد است'))}else a.push(c)});req.on('end',()=>resolve(Buffer.concat(a)));req.on('error',reject)})}
function jsonBody(buf){try{return JSON.parse(buf.toString('utf8'))}catch{return {}}}
function parseMultipart(buf,ct){const b=ct.match(/boundary=(?:"([^"]+)"|([^;]+))/i)?.[1]||ct.match(/boundary=(?:"([^"]+)"|([^;]+))/i)?.[2];if(!b)throw Error('فرمت آپلود نامعتبر است');const boundary=Buffer.from('--'+b), parts=[];let p=0;while((p=buf.indexOf(boundary,p))>=0){p+=boundary.length;if(buf.slice(p,p+2).toString()==='--')break;if(buf.slice(p,p+2).toString()==='\r\n')p+=2;const e=buf.indexOf(Buffer.from('\r\n\r\n'),p);if(e<0)break;const h=buf.slice(p,e).toString('utf8');let q=buf.indexOf(boundary,e+4);if(q<0)break;let dataEnd=q-2;const m=h.match(/name="([^"]+)"/i), f=h.match(/filename="([^"]*)"/i), type=h.match(/Content-Type:\s*([^\r\n]+)/i);if(m)parts.push({name:m[1],filename:f?Buffer.from(f[1],'binary').toString('utf8'):null,type:type?.[1]?.trim()||'',data:buf.slice(e+4,dataEnd)});p=q}return parts}
function clean(v,max=3000){return String(v??'').trim().slice(0,max)}
function mime(ext){return ({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'})[ext]||'application/octet-stream'}
function staticFile(req,res){let u=new URL(req.url,'http://localhost');let f=decodeURIComponent(u.pathname);if(f==='/')f='/index.html';if(f==='/admin' || f==='/admin/')f='/admin/index.html';const file=path.normalize(path.join(PUBLIC,f));if(!file.startsWith(PUBLIC))return text(res,403,'Forbidden');fs.readFile(file,(e,d)=>{if(e)return text(res,404,'Not found');res.writeHead(200,{'Content-Type':mime(path.extname(file).toLowerCase()),'Cache-Control':'no-cache'});res.end(d)})}

async function route(req,res){try{const u=new URL(req.url,'http://localhost');
if(req.method==='POST'&&u.pathname==='/api/admin/login'){const d=jsonBody(await body(req));if(d.username===USER&&d.password===PASS){const sid=crypto.randomBytes(24).toString('hex');sessions.add(sid);return send(res,200,{success:true},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400`})}return send(res,401,{success:false,message:'نام کاربری یا رمز عبور اشتباه است.'})}
if(req.method==='POST'&&u.pathname==='/api/admin/logout'){const s=cookie(req);sessions.delete(s);return send(res,200,{success:true},{'Set-Cookie':'sid=; HttpOnly; Path=/; Max-Age=0'})}
if(u.pathname==='/api/admin/me'&&req.method==='GET')return send(res,200,{loggedIn:admin(req)});
if(u.pathname.startsWith('/api/admin')&&!admin(req))return send(res,401,{success:false,message:'دسترسی غیرمجاز'});
if(req.method==='POST'&&u.pathname==='/api/tickets'){const d=jsonBody(await body(req));if(!clean(d.contact_value,150)||!clean(d.subject,200)||!clean(d.message,5000))return send(res,400,{success:false,message:'اطلاعات تیکت کامل نیست.'});const t={id:db.nextTicket++,contact_type:d.contact_type==='rubika'?'rubika':'discord',contact_value:clean(d.contact_value,150),subject:clean(d.subject,200),message:clean(d.message,5000),status:'open',created_at:new Date().toISOString(),messages:[{from:'customer',message:clean(d.message,5000),created_at:new Date().toISOString()}]};db.tickets.push(t);save();return send(res,200,{success:true,ticketId:t.id})}
if(req.method==='GET'&&u.pathname.startsWith('/api/tickets/')){const id=Number(u.pathname.split('/').pop()),contact=clean(u.searchParams.get('contact'),150),t=db.tickets.find(x=>x.id===id&&x.contact_value===contact);if(!t)return send(res,404,{success:false,message:'تیکت پیدا نشد.'});return send(res,200,t)}
if(req.method==='POST'&&u.pathname.startsWith('/api/tickets/')&&u.pathname.endsWith('/reply')){const id=Number(u.pathname.split('/')[3]),d=jsonBody(await body(req)),contact=clean(d.contact_value,150),t=db.tickets.find(x=>x.id===id&&x.contact_value===contact);if(!t)return send(res,404,{success:false,message:'تیکت پیدا نشد.'});const message=clean(d.message,5000);if(!message)return send(res,400,{success:false,message:'پیام خالی است.'});t.messages=t.messages||[{from:'customer',message:t.message,created_at:t.created_at}];t.messages.push({from:'customer',message,created_at:new Date().toISOString()});t.status='open';save();return send(res,200,{success:true})}
if(req.method==='GET'&&u.pathname==='/api/admin/stats')return send(res,200,{orders:db.orders.length,paid:db.orders.filter(x=>x.payment_status==='paid').length,pending:db.orders.filter(x=>x.status==='processing').length,tickets:db.tickets.filter(x=>x.status==='open').length});
if(req.method==='GET'&&u.pathname==='/api/admin/orders')return send(res,200,db.orders.slice().reverse());
if(req.method==='PUT'&&u.pathname.startsWith('/api/admin/orders/')){const id=Number(u.pathname.split('/').pop()),d=jsonBody(await body(req)),o=db.orders.find(x=>x.id===id);if(!o)return send(res,404,{success:false,message:'سفارش پیدا نشد'});o.status=['pending','processing','completed','cancelled'].includes(d.status)?d.status:o.status;if(d.payment_status==='paid'){o.payment_status='paid';o.status=o.status==='pending'?'processing':o.status}else if(d.payment_status==='rejected'){o.payment_status='rejected'}save();return send(res,200,{success:true})}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/orders/')){const id=Number(u.pathname.split('/').pop()),i=db.orders.findIndex(x=>x.id===id);if(i<0)return send(res,404,{success:false,message:'سفارش پیدا نشد'});const o=db.orders[i];for(const f of [o.skin_file,o.receipt_image]){if(f)try{fs.unlinkSync(path.join(PUBLIC,f.replace(/^\//,'')))}catch{}}db.orders.splice(i,1);save();return send(res,200,{success:true})}
if(req.method==='GET'&&u.pathname==='/api/admin/tickets')return send(res,200,db.tickets.slice().reverse());
if(req.method==='POST'&&u.pathname.startsWith('/api/admin/tickets/')&&u.pathname.endsWith('/reply')){const id=Number(u.pathname.split('/')[4]),d=jsonBody(await body(req)),t=db.tickets.find(x=>x.id===id);if(!t)return send(res,404,{success:false,message:'تیکت پیدا نشد.'});const message=clean(d.message,5000);if(!message)return send(res,400,{success:false,message:'پیام خالی است.'});t.messages=t.messages||[{from:'customer',message:t.message,created_at:t.created_at}];t.messages.push({from:'admin',message,created_at:new Date().toISOString()});t.status='open';save();return send(res,200,{success:true})}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/tickets/')){const id=Number(u.pathname.split('/').pop()),i=db.tickets.findIndex(x=>x.id===id);if(i<0)return send(res,404,{success:false,message:'تیکت پیدا نشد.'});db.tickets.splice(i,1);save();return send(res,200,{success:true})}
if(req.method==='PUT'&&u.pathname.startsWith('/api/admin/tickets/')){const id=Number(u.pathname.split('/').pop()),d=jsonBody(await body(req)),t=db.tickets.find(x=>x.id===id);if(!t)return send(res,404,{success:false});t.status=d.status==='closed'?'closed':'open';save();return send(res,200,{success:true})}
if(req.method==='GET'&&u.pathname==='/api/admin/portfolio')return send(res,200,db.portfolio.slice().reverse());
if(req.method==='POST'&&u.pathname==='/api/admin/portfolio'){const parts=parseMultipart(await body(req),req.headers['content-type']||'');let title='',category='all',file=null;for(const p of parts){if(p.name==='title')title=p.data.toString('utf8');else if(p.name==='category')category=p.data.toString('utf8');else if(p.name==='image'&&p.filename)file=p}if(!title||!file)return send(res,400,{success:false,message:'عنوان و تصویر را وارد کن'});const ext=path.extname(file.filename).toLowerCase();if(!['.png','.jpg','.jpeg','.webp'].includes(ext))return send(res,400,{success:false,message:'فرمت تصویر مجاز نیست'});const fn=Date.now()+'-'+crypto.randomBytes(4).toString('hex')+ext;fs.writeFileSync(path.join(PORTFOLIO,fn),file.data);db.portfolio.push({id:db.nextPortfolio++,title:clean(title,150),category:['bedwars','survival','hardcore','all'].includes(category)?category:'all',image:'/uploads/portfolio/'+fn,created_at:new Date().toISOString()});save();return send(res,200,{success:true})}
if(req.method==='DELETE'&&u.pathname.startsWith('/api/admin/portfolio/')){const id=Number(u.pathname.split('/').pop()),i=db.portfolio.findIndex(x=>x.id===id);if(i<0)return send(res,404,{success:false});const x=db.portfolio[i];try{fs.unlinkSync(path.join(PUBLIC,x.image.replace(/^\//,'')))}catch{}db.portfolio.splice(i,1);save();return send(res,200,{success:true})}
if(req.method==='POST'&&u.pathname==='/api/payment-intent'){const parts=parseMultipart(await body(req),req.headers['content-type']||'');const d={};let file=null;for(const p of parts){if(p.filename)file=p;else d[p.name]=p.data.toString('utf8')}const service=d.service,price=Number(d.price);if(!clean(d.customer_name,100)||!clean(d.contact_value,150)||!services[service]||price!==services[service])return send(res,400,{success:false,message:'اطلاعات سفارش نامعتبر است.'});let skin=null;if(file){const ext=path.extname(file.filename).toLowerCase();if(!['.png','.jpg','.jpeg','.webp'].includes(ext))return send(res,400,{success:false,message:'فرمت اسکین باید PNG/JPG/WEBP باشد.'});if(file.data.length>10*1024*1024)return send(res,400,{success:false,message:'حجم اسکین بیشتر از ۱۰ مگابایت است.'});const fn=Date.now()+'-'+crypto.randomBytes(4).toString('hex')+ext;fs.writeFileSync(path.join(SKINS,fn),file.data);skin='/uploads/skins/'+fn}const token=crypto.randomBytes(24).toString('hex');paymentDrafts.set(token,{customer_name:clean(d.customer_name,100),contact_type:d.contact_type==='rubika'?'rubika':'discord',contact_value:clean(d.contact_value,150),service,price,description:clean(d.description,3000),skin_file:skin,created_at:new Date().toISOString()});setTimeout(()=>paymentDrafts.delete(token),30*60*1000);return send(res,200,{success:true,payment_token:token,amount:price,card_number:'6037997592876966',card_holder:'آرزو براتی کیا'})}
if(req.method==='POST'&&u.pathname==='/api/orders'){return send(res,410,{success:false,message:'برای ثبت سفارش ابتدا پرداخت را انجام دهید.'})}
if(req.method==='POST'&&u.pathname==='/api/payment/confirm'){const parts=parseMultipart(await body(req),req.headers['content-type']||'');const d={};let image=null;for(const part of parts){if(part.name==='receipt_image'&&part.filename)image=part;else d[part.name]=part.data.toString('utf8')}const token=clean(d.payment_token,100),draft=paymentDrafts.get(token);if(!draft)return send(res,400,{success:false,message:'جلسه پرداخت منقضی شده است. دوباره سفارش را شروع کنید.'});if(!image&&!clean(d.receipt_text,5000))return send(res,400,{success:false,message:'عکس واریزی یا متن واریزی را ارسال کن.'});let receiptImage=null;if(image){const ext=path.extname(image.filename).toLowerCase();if(!['.png','.jpg','.jpeg','.webp'].includes(ext))return send(res,400,{success:false,message:'فرمت عکس رسید مجاز نیست.'});if(image.data.length>8*1024*1024)return send(res,400,{success:false,message:'حجم عکس رسید بیشتر از ۸ مگابایت است.'});const fn=Date.now()+'-'+crypto.randomBytes(4).toString('hex')+ext;fs.writeFileSync(path.join(RECEIPTS,fn),image.data);receiptImage='/uploads/receipts/'+fn}const o={id:db.nextOrder++,...draft,receipt_image:receiptImage,receipt_text:clean(d.receipt_text,5000)||null,status:'pending',payment_status:'receipt_submitted',authority:null,ref_id:null};db.orders.push(o);save();paymentDrafts.delete(token);return send(res,200,{success:true,orderId:o.id})}
if(req.method==='POST'&&u.pathname==='/api/payment'){const d=jsonBody(await body(req)),o=db.orders.find(x=>x.id===Number(d.orderId));if(!o)return send(res,404,{success:false,message:'سفارش پیدا نشد.'});return send(res,200,{success:true,manual:true,orderId:o.id,card_number:'6037997592876966',card_holder:'آرزو براتی کیا',amount:o.price})}
if(req.method==='GET'&&u.pathname==='/api/portfolio')return send(res,200,db.portfolio.slice().reverse());
return staticFile(req,res);
}catch(e){console.error(e);send(res,500,{success:false,message:e.message||'خطای سرور'})}}
const server=http.createServer(route);
function startServer(port){
  server.once('error', err=>{
    if(err.code==='EADDRINUSE'){
      console.error('Port 3001 is already in use. Close the previous P.o.uGfx server and run START_SITE.bat again.');
    } else console.error(err);
    process.exit(1);
  });
  server.listen(port,'0.0.0.0',()=>{
    fs.writeFileSync(path.join(ROOT,'runtime-port.txt'),'3001','utf8');
    fs.writeFileSync(path.join(ROOT,'pid'),String(process.pid),'utf8');
    console.log(`P.o.uGfx v6 running at http://127.0.0.1:3001`);
  });
}
startServer(3001);
